services:
  my_vllm_container:
    image: vllm/vllm-openai:arm
    container_name: deepseek-R1-14B
    #platform: linux/amd64
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./start.sh:/app/start.sh
      - ./main.py:/app/main.py
    ports:
      - "8000:8000"
    ipc: host
    #working_dir: /app
    #entrypoint: ["/bin/bash", "-c"]
    #command: "/app/start.sh"
    #command: ["/bin/bash", "/app/start.sh"]
    #command: --model deepseek-ai/DeepSeek-R1-Distill-Qwen-14B

